name: evanlaw
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7548379593063146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.817426476161927
  lightness: 0.1700038299895823
  saturation: 0.29187112767249346
  rhythmicContrast: 0.46498737670481205
purpose: []
